<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250711192922 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bill (
          vat DOUBLE PRECISION NOT NULL,
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          user_id BIGINT DEFAULT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_7A2119E3A76ED395 ON bill (user_id)');
        $this->addSql('CREATE TABLE bill_line_product (
          quantity SMALLINT NOT NULL,
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          slug VARCHAR(255) DEFAULT NULL,
          bill_id BIGINT NOT NULL,
          product_id BIGINT NOT NULL,
          bill_type VARCHAR(255) NOT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_182EE6CF989D9B62 ON bill_line_product (slug)');
        $this->addSql('CREATE INDEX IDX_182EE6CF1A8C12F5 ON bill_line_product (bill_id)');
        $this->addSql('CREATE INDEX IDX_182EE6CF4584665A ON bill_line_product (product_id)');
        $this->addSql('CREATE TABLE brands (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          name VARCHAR(255) NOT NULL,
          slug VARCHAR(255) DEFAULT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7EA24434989D9B62 ON brands (slug)');
        $this->addSql('CREATE TABLE campaign_products (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          campaign_id BIGINT NOT NULL,
          campaign_type VARCHAR(255) NOT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_81CA8C25F639F774 ON campaign_products (campaign_id)');
        $this->addSql('CREATE TABLE campaign_product_product (
          campaign_product_id BIGINT NOT NULL,
          product_id BIGINT NOT NULL,
          PRIMARY KEY (campaign_product_id, product_id)
        )');
        $this->addSql('CREATE INDEX IDX_7F249008829346F2 ON campaign_product_product (campaign_product_id)');
        $this->addSql('CREATE INDEX IDX_7F2490084584665A ON campaign_product_product (product_id)');
        $this->addSql('CREATE TABLE campaigns (
          starts_at DATE NOT NULL,
          ends_at DATE NOT NULL,
          discount SMALLINT NOT NULL,
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          slug VARCHAR(255) DEFAULT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E3737470989D9B62 ON campaigns (slug)');
        $this->addSql('CREATE TABLE cloth_campaign_product (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cloth_product (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cloth_product_bill_line (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cloth_product_image (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE food_campaign_product (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE food_product (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE food_product_bill_line (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE food_product_image (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE home_campaign_product (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE home_product (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE home_product_bill_line (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE home_product_image (id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE images (
          url VARCHAR(255) NOT NULL,
          alt VARCHAR(255) NOT NULL,
          title VARCHAR(255) NOT NULL,
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE TABLE product_images (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          image_id BIGINT NOT NULL,
          product_id BIGINT NOT NULL,
          image_type VARCHAR(255) NOT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_8263FFCE3DA5256D ON product_images (image_id)');
        $this->addSql('CREATE INDEX IDX_8263FFCE4584665A ON product_images (product_id)');
        $this->addSql('CREATE TABLE products (
          description VARCHAR(1024) NOT NULL,
          more_info VARCHAR(1024) DEFAULT NULL,
          price DOUBLE PRECISION NOT NULL,
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255) NOT NULL,
          slug VARCHAR(255) DEFAULT NULL,
          created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
          brand_id BIGINT NOT NULL,
          product_type VARCHAR(255) NOT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3BA5A5A989D9B62 ON products (slug)');
        $this->addSql('CREATE INDEX IDX_B3BA5A5A44F5D008 ON products (brand_id)');
        $this->addSql('CREATE TABLE "user" (
          email VARCHAR(180) NOT NULL,
          roles JSON NOT NULL,
          password VARCHAR(255) NOT NULL,
          is_verified BOOLEAN NOT NULL,
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE
          bill
        ADD
          CONSTRAINT FK_7A2119E3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE
          bill_line_product
        ADD
          CONSTRAINT FK_182EE6CF1A8C12F5 FOREIGN KEY (bill_id) REFERENCES bill (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE
          bill_line_product
        ADD
          CONSTRAINT FK_182EE6CF4584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE
          campaign_products
        ADD
          CONSTRAINT FK_81CA8C25F639F774 FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE
          campaign_product_product
        ADD
          CONSTRAINT FK_7F249008829346F2 FOREIGN KEY (campaign_product_id) REFERENCES campaign_products (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE
          campaign_product_product
        ADD
          CONSTRAINT FK_7F2490084584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          cloth_campaign_product
        ADD
          CONSTRAINT FK_AEDB9E7CBF396750 FOREIGN KEY (id) REFERENCES campaign_products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          cloth_product
        ADD
          CONSTRAINT FK_88008F82BF396750 FOREIGN KEY (id) REFERENCES products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          cloth_product_bill_line
        ADD
          CONSTRAINT FK_8F72CF76BF396750 FOREIGN KEY (id) REFERENCES bill_line_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          cloth_product_image
        ADD
          CONSTRAINT FK_C0ED306BBF396750 FOREIGN KEY (id) REFERENCES product_images (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          food_campaign_product
        ADD
          CONSTRAINT FK_58252774BF396750 FOREIGN KEY (id) REFERENCES campaign_products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          food_product
        ADD
          CONSTRAINT FK_9CD5D895BF396750 FOREIGN KEY (id) REFERENCES products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          food_product_bill_line
        ADD
          CONSTRAINT FK_815FB9FDBF396750 FOREIGN KEY (id) REFERENCES bill_line_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          food_product_image
        ADD
          CONSTRAINT FK_5EA85394BF396750 FOREIGN KEY (id) REFERENCES product_images (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          home_campaign_product
        ADD
          CONSTRAINT FK_100C9BD4BF396750 FOREIGN KEY (id) REFERENCES campaign_products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          home_product
        ADD
          CONSTRAINT FK_666ACFF5BF396750 FOREIGN KEY (id) REFERENCES products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          home_product_bill_line
        ADD
          CONSTRAINT FK_57C133A9BF396750 FOREIGN KEY (id) REFERENCES bill_line_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          home_product_image
        ADD
          CONSTRAINT FK_79DEBF96BF396750 FOREIGN KEY (id) REFERENCES product_images (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE
          product_images
        ADD
          CONSTRAINT FK_8263FFCE3DA5256D FOREIGN KEY (image_id) REFERENCES images (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE
          product_images
        ADD
          CONSTRAINT FK_8263FFCE4584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE
          products
        ADD
          CONSTRAINT FK_B3BA5A5A44F5D008 FOREIGN KEY (brand_id) REFERENCES brands (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bill DROP CONSTRAINT FK_7A2119E3A76ED395');
        $this->addSql('ALTER TABLE bill_line_product DROP CONSTRAINT FK_182EE6CF1A8C12F5');
        $this->addSql('ALTER TABLE bill_line_product DROP CONSTRAINT FK_182EE6CF4584665A');
        $this->addSql('ALTER TABLE campaign_products DROP CONSTRAINT FK_81CA8C25F639F774');
        $this->addSql('ALTER TABLE campaign_product_product DROP CONSTRAINT FK_7F249008829346F2');
        $this->addSql('ALTER TABLE campaign_product_product DROP CONSTRAINT FK_7F2490084584665A');
        $this->addSql('ALTER TABLE cloth_campaign_product DROP CONSTRAINT FK_AEDB9E7CBF396750');
        $this->addSql('ALTER TABLE cloth_product DROP CONSTRAINT FK_88008F82BF396750');
        $this->addSql('ALTER TABLE cloth_product_bill_line DROP CONSTRAINT FK_8F72CF76BF396750');
        $this->addSql('ALTER TABLE cloth_product_image DROP CONSTRAINT FK_C0ED306BBF396750');
        $this->addSql('ALTER TABLE food_campaign_product DROP CONSTRAINT FK_58252774BF396750');
        $this->addSql('ALTER TABLE food_product DROP CONSTRAINT FK_9CD5D895BF396750');
        $this->addSql('ALTER TABLE food_product_bill_line DROP CONSTRAINT FK_815FB9FDBF396750');
        $this->addSql('ALTER TABLE food_product_image DROP CONSTRAINT FK_5EA85394BF396750');
        $this->addSql('ALTER TABLE home_campaign_product DROP CONSTRAINT FK_100C9BD4BF396750');
        $this->addSql('ALTER TABLE home_product DROP CONSTRAINT FK_666ACFF5BF396750');
        $this->addSql('ALTER TABLE home_product_bill_line DROP CONSTRAINT FK_57C133A9BF396750');
        $this->addSql('ALTER TABLE home_product_image DROP CONSTRAINT FK_79DEBF96BF396750');
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT FK_8263FFCE3DA5256D');
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT FK_8263FFCE4584665A');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5A44F5D008');
        $this->addSql('DROP TABLE bill');
        $this->addSql('DROP TABLE bill_line_product');
        $this->addSql('DROP TABLE brands');
        $this->addSql('DROP TABLE campaign_products');
        $this->addSql('DROP TABLE campaign_product_product');
        $this->addSql('DROP TABLE campaigns');
        $this->addSql('DROP TABLE cloth_campaign_product');
        $this->addSql('DROP TABLE cloth_product');
        $this->addSql('DROP TABLE cloth_product_bill_line');
        $this->addSql('DROP TABLE cloth_product_image');
        $this->addSql('DROP TABLE food_campaign_product');
        $this->addSql('DROP TABLE food_product');
        $this->addSql('DROP TABLE food_product_bill_line');
        $this->addSql('DROP TABLE food_product_image');
        $this->addSql('DROP TABLE home_campaign_product');
        $this->addSql('DROP TABLE home_product');
        $this->addSql('DROP TABLE home_product_bill_line');
        $this->addSql('DROP TABLE home_product_image');
        $this->addSql('DROP TABLE images');
        $this->addSql('DROP TABLE product_images');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE "user"');
    }
}
